version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
    image: php:apache-bullseye
    container_name: php_apache
    environment:
      - MYSQL_DATABASE=tech_db
      - MYSQL_USER=theFirstUser
      - MYSQL_PASSWORD=theFirstUser1234
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD= "135792468"
      - MYSQL_DATABASE=tech_db
      - MYSQL_USER=theFirstUser
      - MYSQL_PASSWORD=theFirstUser1234
    ports:
      - "3007:3006"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: